Add Metabase and monitoring namespace
spack/spack-infrastructure pull request #157
Opened 2021-11-15 18:12 UTC by kotfic

2021-11-15 18:12 UTC, kotfic commented
@opadron PTAL - thanks!

2021-11-18 21:05 UTC, opadron requested changes

2021-11-18 21:05 UTC, opadron commented on k8s/metabase/postgres-service.yaml
> +  type: NodePort
This should be a `ClusterIP` service.

2021-11-22 17:30 UTC, opadron approved these changes

2021-11-22 18:22 UTC, merged