[WIP] GLR to explore job resource requests and limits
spack/spack-infrastructure pull request #217
Opened 2022-03-01 21:11 UTC by kotfic

2022-03-01 21:16 UTC, opadron requested changes
Mostly nitpicks, but we want to be sure to get all the naming right.

2022-03-01 21:16 UTC, opadron commented on k8s/runners/glr-glr-test/release.yaml
> +---
Can you move this to `k8s/runners/glr-testing-x86-pub`?

2022-03-01 21:16 UTC, opadron commented on k8s/runners/glr-glr-test/release.yaml
> +  name: runner-glr-test
runner-glr-testing-x86-pub

2022-03-01 21:16 UTC, opadron commented on k8s/runners/glr-glr-test/release.yaml
> +  releaseName: glr-test
glr-testing-x86-pub

2022-03-01 21:16 UTC, opadron commented on k8s/runners/glr-glr-test/release.yaml
> +              "spack.io/node-pool" = "glr-glr-test"
glr-glr-testing

2022-03-01 21:22 UTC, opadron approved these changes

2022-03-03 21:01 UTC, kotfic commented
FYI:  This is still an experimental work in progress -  please also considering looking at the actual Helm Release.  Also *This PR should not be merged*

2025-02-06 03:00 UTC, mvandenburgh commented
We've added resource requests to the Gitlab runners since this PR was opened.

2025-02-06 03:00 UTC, closed without merging