add additional job labels to all build job pods
spack/spack-infrastructure pull request #626
Opened 2023-09-15 16:39 UTC by cmelone

This change adds the following information to the job metadata:
- package version
- compiler name
- compiler version
- arch
- package variants

let me know if i'm missing anything

cc: @alecbcs

2023-09-15 16:55 UTC, scottwittenburg requested changes
I requested to remove these labels from the `signing` runner, but otherwise this looks good to me, thanks @cmelone!

2023-09-15 16:55 UTC, scottwittenburg commented on k8s/production/runners/signing/release.yaml
> +              "metrics/spack_job_spec_variants" = "$SPACK_JOB_SPEC_VARIANTS"
These variables aren't applicable to this particular job, it runs at the end of each child pipeline and operates on all the specs in the mirror.

2023-09-15 22:06 UTC, scottwittenburg approved these changes

2023-09-15 22:07 UTC, merged

2023-09-16 15:07 UTC, cmelone commented
Hmm, this might be a problem for parsing. These variants: 

```
~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared
      build_system=makefile symbol_suffix=none threads=openmp
```

get displayed as this in prometheus:

```
bignuma_consistent_fpcsr_fortran_ilp64_locking_pic_shared_build
```

I think the main issue is that there is no way to distinguish between `~` and `+` when it gets converted to the underscore format.

2023-09-18 18:40 UTC, scottwittenburg commented
> but this adds an additional request per job to my collection script, slowing down the execution quite a bit

This also adds to the load on gitlab, which can already struggle to handle requests at busy times (like early this morning).

> Not sure if this is a limitation inherent to Prometheus, or if this is something I can help resolve.

I'm not at all a prometheus expert, if you can find a way to avoid the mangling of strings, that would be great.

We could also consider if some kind of encoding (eg base64 or url) could help here.  I'm just not sure what characters or formats prometheus can't handle, forcing it to add the underscores.